### ISSUE TITLE
Browser not supported

### ISSUE THREAD

**Issue by scottjbarr** [karmainside/ms-teams-linux#3]
Hi

As of this morning the MS Teams web app reports the browser as unsupported.

![screenshot from 2017-12-12 08-14-31](https://user-images.githubusercontent.com/15627/33856696-a685dfee-df14-11e7-83f3-f8a69dfe9ecb.png)

This is really unfortunate because if you run Teams in Chrome you don't get notifications on the desktop.

**Comment by karmainside** [comment]
Hi, thanks for the information.
It is happening because of outdated chromium browser used in the application by electron.
Please, try the [latest release 0.5.1](https://github.com/karmainside/ms-teams-linux/releases/tag/v.0.5.1) and let me know if it works.

**Comment by ofayans** [comment]
release 0.5.1 also does not work. Error message is the same

**Comment by telamon** [comment]
![screenshot from 2017-12-12 12-40-22](https://user-images.githubusercontent.com/148454/33882850-da84e84c-df39-11e7-8237-d673fb90ee36.png)

Yeah just downloaded the 0.5.1 app-image and can confirm that it dosen't work. 

Goddamn my hate for Microsoft and their constant incompetence runs so deep I'm seriously considering ordering an ethnic cleanse of anyone ever associated to that company - given that I ever get into some serious political power that is.  So live you bastards, breathe while you can.. But meanwhile, do we know what triggers the browser-unsupported event? 

Is it based on browser-capabilities or just plain incompetence of parsing the the user-agent?

**Comment by karmainside** [comment]
@telamon , can you please re-download [this one](https://github.com/karmainside/ms-teams-linux/releases/download/v.0.5.1/ms-teams-capsule-0.5.1-x86_64.AppImage) again? Should be working now.

**Comment by telamon** [comment]
@karmainside Good job man, It works!

**Comment by dskopa-softdev** [comment]
@karmainside the link https://github.com/karmainside/ms-teams-linux/releases/download/v.0.5.1/ms-teams-capsule-0.5.1-x86_64.AppImage doesn't exist anymore. There is only 0.4.0 version here and it gives  the same "Your browser version isn't supported" error

**Comment by dskopa-softdev** [comment]
oh, i see there is extra `v` in the link before the version, the link should be  https://github.com/karmainside/ms-teams-linux/releases/download/0.5.1/ms-teams-capsule-0.5.1-x86_64.AppImage

**Comment by karmainside** [comment]
@dskopa-softdev thanks for an update! Links in Readme are updated.
